name: message_me
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  build_runner: ^2.7.0
  cloud_firestore: ^6.0.0
  connectivity_plus: ^6.1.5
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.5.0
  dio: ^5.9.0
  file_picker: ^10.3.2
  firebase_analytics: ^12.0.0
  firebase_app_check: ^0.4.0+1
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.1
  firebase_remote_config: ^6.0.1
  firebase_storage: ^13.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_image_compress: ^2.4.0
  flutter_keyboard_visibility: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  flutter_screenutil: ^5.9.3
  flutter_spinkit: ^5.2.2
  get_it: ^8.2.0
  image_gallery_saver_plus: ^4.0.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  json_serializable: ^6.10.0
  package_info_plus: ^8.3.1
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  timeago: ^3.7.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true # The name of the icon file in mipmap folders
  ios: true # Generate icons for iOS
  image_path: "assets/images/message_me_logo.png" # Path to your source icon
  min_sdk_android: 21 # Optional: For adaptive icons
  adaptive_icon_background: "#1F2C34"
  adaptive_icon_foreground: "assets/images/message_me_logo.png"
